### ISSUE TITLE
dawn calculation problem

### ISSUE THREAD

**Issue by bhikkhu-kosalla-china** [vpnry/upcal#1]
dawn time cannot use sun rise -40 min, it is too rough.
From Dawnrise to Sunrise is the time of the sun passing 6 degree ≈ 24 hour *6/360
different day the sun angle is different, so the accurate time is changing everyday.
fortunately, [suncalc](https://github.com/mourner/suncalc) support calculate the dawn time.
Just use the civil dawn time to replace sunrise, ignore -40mins.

**Comment by vpnry** [comment]
Thanks. Sādhu x3. 

Now on trip.
Will get back…

**Comment by vpnry** [comment]
The app also had the formula: Dawnrise = Sunrise - (Civil dawn - Nautical dawn)
